function [data] = support_design(k, fn, ...
                                dmin, dmax, ...
                                Dmin, Dmax, ...
                                nmin, nmax, ...
                                fbmin, fbmax)
%SUPPORT_DESIGN 此处显示有关此函数的摘要
%   此处显示详细说明
    command = sprintf("python support_design.py %f %f %f %f" + ...
        " %f %f %f %f %f %f", k, fn, dmin, dmax, Dmin, Dmax, ...
        nmin, nmax, fbmin, fbmax);
    system(command);
    fileContent = fileread("support_design.json");
    data = jsondecode(fileContent);
end

